# Generated by Django 4.2.6 on 2023-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='segmento',
            field=models.CharField(choices=[('Comunidad USM', 'Comunidad USM'), ('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Jefe de Carrera', 'Jefe de Carrera')], max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Feriado', 'Feriado'), ('Suspensión de actividades', 'Suspensión de actividades'), ('Suspensión de actividades PM', 'Suspensión de actividades PM'), ('Periodo Lectivo', 'Periodo Lectivo'), ('Suspensión de evaluaciones', 'Suspensión de evaluaciones'), ('Ceremonio', 'Ceremonio'), ('EDDA', 'EDDA'), ('Evaluación', 'Evaluación'), ('Ayudantías', 'Ayudantías'), ('Hito Académico', 'Hito Académico'), ('Secretaria Académica', 'Secretaria Académica'), ('OAI', 'OAI')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Segmento',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
