# Generated by Django 4.2.6 on 2023-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_evento_segmento_alter_evento_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_segmento', models.CharField(choices=[('Comunidad USM', 'Comunidad USM'), ('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Jefe de Carrera', 'Jefe de Carrera')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='segmento',
        ),
        migrations.AddField(
            model_name='evento',
            name='segmento',
            field=models.ManyToManyField(to='app.segmento'),
        ),
    ]
