# Generated by Django 4.2.6 on 2023-11-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_segmento_remove_evento_segmento_evento_segmento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmento',
            old_name='nombre_segmento',
            new_name='segmento_nombre',
        ),
    ]
